version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: springboot_app
    restart: always
    env_file:
      - .env
    ports:
      - "${SERVER_PORT2}:${SERVER_PORT2}"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE2_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SERVER_PORT: ${SERVER_PORT2}
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: